<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $products = [
            [
                'name' => 'Chicken Tikka Masala',
                'vendor_id' => 1,
                'category_id' => 1,
                'description' => 'Creamy tomato-based curry with tender chicken pieces, aromatic spices, and basmati rice',
                'cuisine' => 'Indian',
                'price' => 18.99,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mediterranean Quinoa Bowl',
                'vendor_id' => 1,
                'category_id' => 1,
                'description' => 'Healthy quinoa bowl with fresh vegetables, feta cheese, olives, and olive oil dressing',
                'cuisine' => 'Mediterranean',
                'price' => 15.50,
                'original_price' => 16.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Japanese Ramen',
                'vendor_id' => 2,
                'category_id' => 2,
                'description' => 'Rich tonkotsu broth with fresh ramen noodles, chashu pork, and seasonal vegetables',
                'cuisine' => 'Japanese',
                'price' => 16.75,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Caesar Salad',
                'vendor_id' => 2,
                'category_id' => 2,
                'description' => 'Fresh romaine lettuce with parmesan cheese, croutons, and classic caesar dressing',
                'cuisine' => 'American',
                'price' => 12.99,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegetable Stir Fry',
                'vendor_id' => 1,
                'category_id' => 1,
                'description' => 'Fresh seasonal vegetables stir-fried with garlic, ginger, and soy sauce over jasmine rice',
                'cuisine' => 'Asian',
                'price' => 14.25,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Margherita Pizza',
                'vendor_id' => 1,
                'category_id' => 1,
                'description' => 'Wood-fired pizza with fresh mozzarella, basil, and San Marzano tomato sauce',
                'cuisine' => 'Italian',
                'price' => 17.50,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fish Tacos',
                'vendor_id' => 2,
                'category_id' => 2,
                'description' => 'Grilled white fish with cabbage slaw, pico de gallo, and chipotle aioli in corn tortillas',
                'cuisine' => 'Mexican',
                'price' => 16.25,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Thai Green Curry',
                'vendor_id' => 3,
                'category_id' => 2,
                'description' => 'Spicy green curry with coconut milk, Thai basil, vegetables, and your choice of protein',
                'cuisine' => 'Thai',
                'price' => 17.99,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Greek Gyro Plate',
                'vendor_id' => 3,
                'category_id' => 2,
                'description' => 'Seasoned lamb and beef with tzatziki, pita bread, Greek salad, and lemon potatoes',
                'cuisine' => 'Greek',
                'price' => 19.50,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Vegetable Pasta Primavera',
                'vendor_id' => 1,
                'category_id' => 1,
                'description' => 'Fresh seasonal vegetables with penne pasta in a light garlic and herb olive oil sauce',
                'cuisine' => 'Italian',
                'price' => 15.75,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Korean BBQ Bowl',
                'vendor_id' => 1,
                'category_id' => 1,
                'description' => 'Marinated beef bulgogi with steamed rice, kimchi, and assorted Korean banchan',
                'cuisine' => 'Korean',
                'price' => 18.25,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moroccan Tagine',
                'vendor_id' => 2,
                'category_id' => 2,
                'description' => 'Slow-cooked chicken with apricots, almonds, and aromatic spices served with couscous',
                'cuisine' => 'Moroccan',
                'price' => 20.99,
                'original_price' => 20.99,
                'stock' => 10,
                'status' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}